name: Remove stale staging resources

# **What it does**:
# This cleans up any rogue staging applications and environments that outlasted
# the closure of their corresponding pull requests.
# **Why we have it**:
# Staging applications and environments sometimes fail to be destroyed when
# their corresponding pull request is closed or merged.
# **Who does it impact**:
# Anyone with a closed, spammy, or deleted pull request in docs or docs-internal.

on:
  schedule:
    - cron: '15,45 * * * *' # every thirty minutes at :15 and :45

permissions:
  contents: read
  pull-requests: read

jobs:
  remove_stale_staging_apps:
    name: Remove stale staging apps
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16.8.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: script/remove-stale-staging-apps.js
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remove_stale_staging_envs:
    name: Remove stale staging environments
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup Node
        uses: actions/setup-node@Search 9ced9a43a244f3ac94f1… 
on blockchair.coSearch m9ced9a43a244f3ac94f… 
on blockchair.coSearch mm9ced9a43a244f3ac94… 
on blockchair.coSearch mmm9ced9a43a244f3ac9… 
on blockchair.coSearch mmmm9ced9a43a244f3ac… 
on blockchair.coSearch mmmmm9ced9a43a244f3a… 
on blockchair.coSearch mmmmmm9ced9a43a244f3… 
on blockchair.coSearch mmmmmmm9ced9a43a244f… 
on blockchair.coSearch mmmmmmmm9ced9a43a244… 
on blockchair.coSearch mmmmmmmmm9ced9a43a24… 
on blockchair.coSearch mmmmmmmmmm9ced9a43a2… 
on blockchair.coSearch mmmmmmmmmmm9ced9a43a… 
on blockchair.coSearch mmmmmmmmmmmm9ced9a43… 
on blockchair.coSearch mmmmmmmmmmmmm9ced9a4… 
on blockchair.coSearch mmmmmmmmmmmmmm9ced9a… 
on blockchair.coSearch mmmmmmmmmmmmmmm9ced9… 
on blockchair.coSearch mmmmmmmmmmmmmmmm9ced… 
on blockchair.coSearch mmmmmmmmmmmmmmmmm9ce… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmm9c… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmm9… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.commmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16.8.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: script/remove-stale-staging-envs.js
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_FR }}
          REPO: ${{ github.repository }}
